
# Have to check which of the hook is responsible fo changing (i think isort is responsible for that)
# reverse('forgot-password',
#                                   kwargs={
#                                       'encoded_pk':
#                                       urlsafe_base64_encode(
#                                           force_bytes(user.id)),
#                                       'token':
#                                       token
#                                   })
# have to comment flake

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.31.0
    hooks:
      - id: yapf
        additional_dependencies: [toml]
  # - repo: https://github.com/pycqa/flake8
  #   rev: 4.0.1
    # hooks:
    #   - id: flake8
    #     additional_dependencies:
    #       - flake8-bugbear
    #       - flake8-builtins
    #       - flake8-coding
    #       - flake8-import-order
    #       - flake8-polyfill
    #       - flake8-quotes
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: 'v0.910'
  #   hooks:
  #     - id: mypy
  #       additional_dependencies: [types-requests, types-PyYAML, types-toml]
